version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app
      - /app/.venv # Evita sobreescribir el entorno virtual del contenedor
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///app/data/alfred.db
      - JWT_SECRET=8f50c0e14db8cf4b840e6c60207a602eb6b5b1481e1e07b77df7f739dfb32525
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita sobreescribir las dependencias de node del contenedor
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0
