import type React from 'react';

// Shared by TaskDetailModal and its sections (TaskDetailSections).
export const styles: Record<string, React.CSSProperties> = {
  modalCreatedHint: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    marginTop: '2px',
  },
  parentRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  parentLink: {
    flex: 1,
    background: 'rgba(255,255,255,0.06)',
    border: '1px solid rgba(255,255,255,0.12)',
    color: 'var(--text-primary)',
    textAlign: 'left',
    padding: '8px 12px',
    fontSize: '13px',
    borderRadius: '6px',
    cursor: 'pointer',
  },
  parentDetach: {
    background: 'transparent',
    border: '1px solid rgba(255,255,255,0.12)',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    fontSize: '14px',
    padding: '4px 10px',
    borderRadius: '6px',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modal: {
    width: '100%',
    // Doubled from 500 → 1000 to host the markdown description and
    // attachment grid without the form feeling cramped. Caps at the
    // viewport width on smaller screens via the responsive max calc.
    maxWidth: 'min(1000px, 95vw)',
    maxHeight: '90vh',
    overflowY: 'auto',
    padding: '30px',
  },
  markdownHint: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    fontWeight: 400,
    marginLeft: '6px',
  },
  descriptionView: {
    minHeight: '60px',
    padding: '10px 14px',
    background: 'rgba(255,255,255,0.04)',
    border: '1px solid rgba(255,255,255,0.10)',
    borderRadius: '6px',
    cursor: 'text',
  },
  descriptionEmpty: {
    color: 'var(--text-muted)',
    fontSize: '13px',
    fontStyle: 'italic',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  modalClose: {
    background: 'transparent',
    border: 'none',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    fontSize: '16px',
  },
  modalForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '12px',
    fontWeight: 600,
    color: 'var(--text-secondary)',
  },
  modalRow: {
    display: 'flex',
    gap: '16px',
  },
  focusAccumulated: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    border: '1px solid var(--glass-border)',
    padding: '12px 16px',
    borderRadius: 'var(--border-radius-sm)',
    fontSize: '13px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '10px',
  },
  autosaveHint: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    fontStyle: 'italic',
  },
  tagPickerRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  tagPickerChip: {
    padding: '4px 10px',
    fontSize: '12px',
    borderRadius: '999px',
    cursor: 'pointer',
  },
  tagPickerChipActive: {
    background: 'rgba(99,102,241,0.18)',
    borderColor: 'rgba(99,102,241,0.45)',
    color: '#ffffff',
  },
  tagPickerEmpty: {
    fontSize: '12px',
    color: 'var(--text-muted)',
    fontStyle: 'italic',
  },
  tagCreateForm: {
    display: 'flex',
    gap: '6px',
    marginTop: '10px',
  },
  tagCreateInput: {
    flex: 1,
    padding: '6px 10px',
    fontSize: '12px',
  },
  tagCreateBtn: {
    padding: '6px 12px',
    fontSize: '12px',
  },
  modalDangerGroup: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  movePickerBox: {
    padding: '12px 14px',
    marginTop: '6px',
    background: 'rgba(255,255,255,0.03)',
    border: '1px solid var(--glass-border)',
    borderRadius: 'var(--border-radius-sm)',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  movePickerRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  movePickerSelect: {
    flex: 1,
    minWidth: '140px',
    padding: '8px 10px',
    fontSize: '13px',
  },
  movePickerSubmit: {
    padding: '8px 16px',
    fontSize: '13px',
  },
  movePickerEmpty: {
    fontSize: '12px',
    color: 'var(--text-muted)',
    fontStyle: 'italic',
  },
  reminderList: {
    listStyle: 'none',
    padding: 0,
    margin: '0 0 10px 0',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  reminderItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '8px 10px',
    background: 'rgba(245,158,11,0.06)',
    border: '1px solid rgba(245,158,11,0.30)',
    borderRadius: 'var(--border-radius-sm)',
  },
  reminderBell: { fontSize: '14px' },
  reminderWhen: {
    fontSize: '13px',
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  reminderPast: { color: 'var(--accent-warning)' },
  reminderPastTag: {
    fontSize: '10px',
    background: 'rgba(245,158,11,0.18)',
    color: 'var(--accent-warning)',
    padding: '1px 6px',
    borderRadius: '999px',
    border: '1px solid rgba(245,158,11,0.45)',
  },
  addReminderBtn: {
    width: '100%',
    padding: '8px',
    fontSize: '12px',
  },
  subtaskLabelCount: {
    color: 'var(--text-muted)',
    fontSize: '12px',
    fontWeight: 400,
  },
  subtaskList: {
    listStyle: 'none',
    padding: 0,
    margin: '0 0 10px 0',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  subtaskItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '8px 10px',
    background: 'rgba(255,255,255,0.02)',
    border: '1px solid var(--glass-border)',
    borderRadius: 'var(--border-radius-sm)',
  },
  subtaskCheckbox: {
    width: '16px',
    height: '16px',
    cursor: 'pointer',
    accentColor: 'var(--accent-primary)',
  },
  subtaskTitle: {
    flex: 1,
    fontSize: '13px',
    color: 'var(--text-primary)',
  },
  subtaskTitleDone: {
    color: 'var(--text-muted)',
    textDecoration: 'line-through',
  },
  subtaskPriorityDot: {
    display: 'inline-block',
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    marginRight: '6px',
    verticalAlign: 'middle',
    flexShrink: 0,
  },
  subtaskDueDate: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    marginLeft: '8px',
  },
  subtaskTagHint: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    marginLeft: '4px',
    fontStyle: 'italic',
  },
  subtaskDelete: {
    background: 'transparent',
    border: 'none',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    fontSize: '12px',
  },
  subtaskForm: {
    display: 'flex',
    gap: '6px',
  },
  subtaskInput: {
    flex: 1,
    padding: '8px 10px',
    fontSize: '13px',
  },
  subtaskAddBtn: {
    padding: '8px 14px',
    fontSize: '12px',
  },
};
